source "https://rubygems.org"


gem "sinatra"
gem "mysql2"
gem "mysql2-cs-bind"
gem "erubis"
gem "unicorn"
gem 'newrelic_rpm' # FIXME: this MUST be removed before submit
gem 'rack-lineprof' # FIXME: this MUST be removed before submit

gem 'pry'
